### ISSUE TITLE
[docs] Umbrella issue for docs improvements

### ISSUE THREAD

**Issue by byCedric** [expo/expo#10150]
## Overview

Right now we have some performance issues when exporting the documentation to static pages. This issue is related to all performance and upgrades issues for the docs.

### Upgrade Next 10

- [x] ~~Basic Next upgrade~~ → #10151
- [x] ~~Fix new Next 9 fast refresh warnings~~ → #10172
- [x] ~~Upgrade to Next 10~~ → #12354

### Clean up Next legacy workarounds

- [x] ~~Remove custom `server.js` to use built-in features~~ → #10182
- [x] ~~Remove `@zeit/next-css` plugin to rely on built-in support~~ → #10181 
- [x] ~~Upgrade Emotion to v10~~ → #10256

### Performance issues

- [ ] Find the cause of extreme amount of `fs.statSync` calls
- [ ] Find the cause of extreme babel traverse usage

### UX improvements

- [x] ~~Implement per-page-customizable table of contents on all pages~~ → #10230
- [ ] Unify API reference page heading structures (e.g. API, Methods, Constants, etc)
- [x] ~~Sort the version selector from cutting edge to oldest~~ → #10259
- [ ] ? SDK version on versioned pages isn't obvious when scrolling down
- [ ] ? Add explicit version of packages to the docs (e.g. `x.x.x` tag next to title or `expo install expo-document-picker@x.x.x`)
- [ ] ? Add examples for both TypeScript and JavaScript with tabbar-toggle
- [ ] ? Add tags in headers for methods only available on certain platforms
- [ ] ? Add style-guideline for [props lists like these](https://docs.expo.io/versions/v39.0.0/sdk/app-loading/#props)

### DX improvements

- [x] ~~Move codebase over to TypeScript~~ → #10324
- [ ] Replace custom MDX loader with [`wrapper` from MDX Provider](https://mdxjs.com/guides/wrapper-customization#using-the-wrapper-for-layout)
- [ ] Simplify Github slugger implementation (e.g. with `remark-slug` or `rehype-slug`)
- [ ] Use MDX tooling to validate broken links
- [x] ~~Add `eslint-config-universe`~~ → #10324
- [x] ~~Add ESLint to CI~~ → #10445
- [ ] Break up `next.config.js` into smaller understandable chunks (e.g. `withPreval`, `withMdx`)

### Other improvements

- [x] ~~Scope the usage of Preval to prevent usage messing up the cache~~ → #10174
- [x] ~~Only store the cache in CI to prevent exports with different build ids~~ → #10174
- [x] ~~Upgrade to MDX v1~~ → #10177
- [ ] Replace the `versions/latest` copy with symlink to avoid duplicate pages being built
- [x] ~~Upgrade docs workflow to Node 14~~ → #10175
- [x] ~~Improve crawler methods to index the docs website~~ → #10194 

### Long term stuff

- [ ] [Start preparing for MDX v2 support](https://github.com/mdx-js/mdx/issues/1041)
- [ ] Help Next.js solve the `trailingSlash` and status page issue → [comment](https://github.com/vercel/next.js/issues/16528#issuecomment-691186873)
- [ ] Add account context to inline docs (e.g. account name, projects, orgs)
- [ ] Add forum context to show topics related to modules (see [discussion](https://github.com/expo/expo/discussions/8765))

**Comment by byCedric** [comment]
When testing MDX `2.0.0-next.9`'s performance, I made a simple test to determine the improvement we could expect. It's using more `estree` instead of babel to convert the MDX file to JSX tree.

It's safe to say we should get a performance improvement of about 2x as fast, see details below.

### Find pages with syntax errors

Because MDX v2 is more focused on JSX instead of HTML, the syntax is a bit more strict. When MDX v2 launches, we probably need to refactor and fix these syntax issues. To still test this, I initially parsed everything and ignored the files with errors. ([see this file](https://github.com/expo/expo/files/6592105/mdx-v2-errors.txt))

### Test case

After that, I wrote a simple script that finds and parses the MDX code with v1 and v2.

```
import mdx from '@mdx-js/mdx';
import fs from 'fs';
import glob from 'glob';
import path from 'path';

const cwd = path.resolve('./pages');

const ignored = JSON.parse(fs.readFileSync('./mdx-v2-result.json'));
const files = glob.sync('**/*.md', { cwd }).filter(filesubpath => !ignored[filesubpath]);

const start = Date.now();

files.forEach(filesubpath => {
  const filepath = path.join(cwd, filesubpath);
  const content = fs.readFileSync(filepath, 'utf-8');

  mdx.sync(content, { filepath });
});

const end = Date.now();

console.log(`Done processing ${files.length} files, in ${end - start}ms`);
console.log(`  - on average: ${(end - start) / files.length}ms`);
```

### Results

I repeated the test 5x, and took the average of the runs. A total of 925 files were compiled.

#### MDX v2

- average duration: `7394.4ms`
- average duration per file: `7.9939459459ms`

```
Done processing 925 files, in 7118ms
  - on average: 7.695135135135135ms
Done processing 925 files, in 7025ms
  - on average: 7.594594594594595ms
Done processing 925 files, in 7751ms
  - on average: 8.37945945945946ms
Done processing 925 files, in 7703ms
  - on average: 8.327567567567568ms
Done processing 925 files, in 7375ms
  - on average: 7.972972972972973ms
```

#### MDX v1

- average duration: `16312.2ms`
- average duration per file: `17.6348108108ms`

```
Done processing 925 files, in 18646ms
  - on average: 20.15783783783784ms
Done processing 925 files, in 15271ms
  - on average: 16.50918918918919ms
Done processing 925 files, in 15423ms
  - on average: 16.673513513513512ms
Done processing 925 files, in 15404ms
  - on average: 16.65297297297297ms
Done processing 925 files, in 16817ms
  - on average: 18.18054054054054ms
```
