### ISSUE TITLE
ImagePicker: various improvements

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#163]
- [x] Return base64: https://github.com/expo/expo-sdk/issues/10
- [x] Include GPS coordinates: https://github.com/expo/expo-sdk/issues/9
- [x] Rotated photos on Android: https://github.com/expo/expo-sdk/issues/25
- [x] Return timestamp, other metadata: https://github.com/expo/expo/issues/80
- [x] Add documentation for quality option: https://github.com/expo/expo-docs/pull/25

**Comment by nikki93** [comment]
Looking on track for SDK 18, will close when released.

**Comment by sriram-dev** [comment]
@nikki93 What is the expected release date of SDK 18 ?

**Comment by nikki93** [comment]
@sriram-dev it's released now. 😮

**Comment by cseelus** [comment]
Neither the exif, nor the base64 option work for me (Expo 18.0.4).

I use it like this:

``` javascript
  _pickImage = async () => {
    let pickerResult = await Expo.ImagePicker.launchImageLibraryAsync({
      exif: true,
      allowsEditing: false,
      quality: 0.7,
      base64: true,
    })

    if (pickerResult.cancelled) {
      return
    }

    console.log(pickerResult)
  }
```

Which logs 

``` javascript
{
  height: 2500,
  origURL: "assets-library://asset/asset.JPG?id=99D53A1F-FEEF-40E1-8BB3-7DD55A43C8B7&ext=JPG",
  cancelled: false,
  width: 1668,
  fileSize: 914208,
  isVertical: true,
  uri: "file:///Users/chris/Library/Developer/CoreSimulator/Devices/998C81E0-5CC6-4A3E-90C2-A7C43060220C/data/Containers/Data/Application/F5960CD1-043E-41DA-83C9-6B9CF180DF09/Library/Caches/ExponentExperienceData/%2540anonymous%252Fcleanguide-c5413b44-e71a-4958-80a6-25b9c9e5d7a5/ImagePicker/19053646-B1DC-4B98-85EB-37233FD0BDB5.jpg"
}

**Comment by brentvatne** [comment]
hello! I just created a brand new project and tried this and it worked as expected: https://github.com/brentvatne/expo-issue-163

i would suggest making sure that your project is updated to sdk 18 properly, you can double check the steps in https://blog.expo.io/expo-sdk-v18-0-0-is-now-available-38e62305283

**Comment by cseelus** [comment]
Thanks @brentvatne, that was indeed the issue.
