### ISSUE TITLE
Release SDK32

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#3030]
## SDK32 release plan

Creating new release issue as it seems like the previous one was accidentally deleted by someone 😱 

@tsapeta 
- [x] Update libs: GestureHandler, Reanimated, Screens #2977 
- [x] Drop SDK25 #2995 
- [x] Update schema on staging
- [x] Version Android code #3003 
- [x] Review changelog #3006
- [x] QA Expo Client on Android #3010 
- [x] Publish prerelease packages
- [x] Publish dev and prod home
- [x] Tag react-native fork `sdk-32.0.0`
- [x] Publish NCL to Apple's account
- [x] Update `expokit-npm-package` #3093
- [x] Push Android Turtle to staging
- [x] Push Android ExpoKit
- [x] Add Android apk
- [x] Release Android in Play Store
- [x] Promote versions to prod
- [x] Mark SDK 25 as deprecated on server

@sjchmiela 
- [x] Drop SDK25 https://github.com/expo/expo/pull/2986
- [x] cherry pick ListView fix from react-native repo (see discussion below)
- [x] Version iOS code https://github.com/expo/expo/pull/2999
- [x] Prepare changelog #3006 
- [x] QA Expo Client on iOS #3010 
- [x] Generate new mocks and update `jest-expo`
- [x] Update `versions` on staging
- [x] Submit for Apple review
- [x] Update ExpoKit on staging
- [x] Rollout Expo Client build for Simulator
- [x] Tag iOS ExpoKit
- [x] Publish packages to npm
- [x] Push schema to production
- [x] Release iOS in App Store
- [x] Update new project templates on staging

@dsokal 
- [x] Release xdl and expo-cli
- [x] Push iOS Turtle to staging
- [x] Release iOS Turtle to prod
- [x] Release Android Turtle to prod
- [x] Release turtle-cli

@esamelson 
- [x] Publish new docs
- [x] Publish blog post with release notes
- [x] Add release notes to docs
- [x] Update website front page
- [x] Post on Twitter
- [x] Publish NCL to @ community account

**Comment by jamespacileo** [comment]
There have been a lot of react-native-web related PRs getting merged, but I don't see any mention of react-native-web support on the milestone release plan.

Are you planning to unofficially release web support as well with this release? Thanks 😄

Just wondering, because that would be awesome!

**Comment by wassgha** [comment]
No background location in this release? #2338

**Comment by ChronSyn** [comment]
> No background location in this release? #2338

Is there any reason it wouldn't be, considering it was merged?

This issue is a checklist of things to be done to release the expo 'platform' to the next SDK version. It doesn't have anything to do with what is included in the release.

**Comment by ide** [comment]
@kevinwolfcr Hooks are not stable in React itself yet. Once hooks are released in a stable version of React, then RN will later upgrade React. Once RN stabilizes, we then have a path to bring hooks to Expo.

@jamespacileo Web is still a ways out and is pre-experimental. When it is ready, we will announce it with the release notes at that time on blog.expo.io.

**Comment by ide** [comment]
I pushed a branch called `sdk-32` (based off of master; feel free to force-push if it needs to point at an older commit) so that new commits to master don't accidentally go out with the release.

**Comment by vractal** [comment]
Hi, im having problems with the expo client since today: 
![image](https://user-images.githubusercontent.com/34239246/50694204-65893700-1020-11e9-9441-d221571a44d9.png)
Perharps it could be  related to this merge?

**Comment by tsapeta** [comment]
@vractal Yes, I'm fixing this issue right now. Sorry for the trouble 😞 The fix will be out soon.

**Comment by vractal** [comment]
@tsapeta Don't worry, thank you!  :)

**Comment by Softrabbit-de** [comment]
> 
> 
> Hi, im having problems with the expo client since today:
> ![image](https://user-images.githubusercontent.com/34239246/50694204-65893700-1020-11e9-9441-d221571a44d9.png)
> Perharps it could be related to this merge?

Just put in app.json:
    "sdkVersion": "32.0.0",
and it should work again :)

**Comment by tonycoco** [comment]
Getting errors with `Unable to resolve "./Amplitude" from "node_modules/expo/build/Expo.js"`

**Comment by burtek** [comment]
When can we expect new docs, release notes and upgrade instructions?

**Comment by esamelson** [comment]
we're working on it! :)

**Comment by burtek** [comment]
@esamelson right, thx for quick reply :

**Comment by isaacnass** [comment]
@burtek [some reading while you wait :)](https://github.com/expo/expo/blob/96d1d58163e9973a53ae572d743308e436ec8def/CHANGELOG.md)

**Comment by burtek** [comment]
@isaacnass THX!!! 😃

**Comment by isaacnass** [comment]
@tonycoco I believe shift + R while in the CLI will do it. Glad you got it working!

**Comment by tonycoco** [comment]
@isaacnass ahh, I meant `shift+r` works fine from within the CLI. But, from the command itself, `expo`, is there a way to force a cache reset?

**Comment by danikane** [comment]
expo start -c

**Comment by andresmtz98** [comment]
Hi. Sorry to write here but there is a critical bug for those who use the "expo-print" module on iOS. I did the post a few days ago. I hope you can review it when you have time and see if with this release you can fix it :3

**Comment by tonycoco** [comment]
https://github.com/expo/vector-icons/pull/74 still needs to be merged too

**Comment by Chanty-SOK** [comment]
Don't this issue have the solution yet?

**Comment by creativemind1** [comment]
> Getting errors with `Unable to resolve "./Amplitude" from "node_modules/expo/build/Expo.js"`

I'm also facing the same issue

**Comment by spyshower** [comment]
What version of RN does this version ship with?

**Comment by zivester** [comment]
I just got an Android update a couple minutes ago (hasn't worked since yesterdays release) and now instead of Blue Screening for incompatibility it hard crashes.  expo@27.0.0 and latest Expo from Play store.

**Comment by jaulz** [comment]
@isaacnaas any chance to include this commit https://github.com/facebook/react-native/commit/cd8051c9398d08fd15088348a5a3d3e6a1c1e35e as well?

**Comment by ChronSyn** [comment]
> @isaacnaas any chance to include this commit [facebook/react-native@cd8051c](https://github.com/facebook/react-native/commit/cd8051c9398d08fd15088348a5a3d3e6a1c1e35e) as well?

The SDK has shipped and the only things still to do appear to documentation. Thus, there's unlikely to be any more cherry-picking for the release, though it may make it into a minor release if the team deem it worthwhile.

**Comment by jaulz** [comment]
@ChronSyn okay, thanks for the feedback anyway!

**Comment by pbandjs** [comment]
> I just got an Android update a couple minutes ago (hasn't worked since yesterdays release) and now instead of Blue Screening for incompatibility it hard crashes. expo@27.0.0 and latest Expo from Play store.

It hard crashes for me with expo@26.0.0 as well.

**Comment by sjchmiela** [comment]
Hey all, thank you for all the consideration and eagerness to try all the new features we've prepared! We really appreciate the enthusiasm! 😍

To let us and you work more efficiently, I'll lock this conversation—please file, as usual, separate GitHub issues for separate problems. For quick questions I would recommend our [Slack community](https://slack.expo.io), which has always been really helpful!

Have a nice day! ☀️
