### ISSUE TITLE
Release SDK33

### ISSUE THREAD

**Issue by sjchmiela** [expo/expo#4154]
## SDK33 release plan

Release branch: [sdk-33](https://github.com/expo/expo/tree/sdk-33)

### SDK code related

- [x] drop obsolete SDKs
- [x] update `react-native-gesture-handler`
- [x] update `lottie-react-native`
- [x] update `react-native-reanimated`
- [x] update `react-native-screens`
- [x] update `@react-native-community/netinfo`
- [x] update `@react-native-community/webview`
- [x] update `react-native-maps`
- [x] update `react-native-svg`
- [x] update `react-native`
- [x] Generate new mocks and update `jest-expo`
- [x] Version Android code (@sjchmiela) (#4270)
- [x] Version iOS code (@tsapeta) (#4249)
- [x] QA Expo Client on iOS (@tsapeta)
- [x] QA Expo Client on Android (@sjchmiela)
- [x] Publish prerelease packages
- [x] Tag react-native fork `sdk-33.0.0` (@ide)
- [x] Tag iOS ExpoKit (@tsapeta)
- [x] Publish `!expo` packages to npm (@sjchmiela)
- [x] Update `expokit-npm-package` (@sjchmiela)
- [x] Publish `react-native-unimodules` to npm (@sjchmiela)
- [x] Publish `expo` to npm (@sjchmiela, @tsapeta)
- [x] Test web in template projects and in general (@EvanBacon)

### Launch blockers
- [x] [android][docs] determine if "mediaTypes" is ignore when launching a camera instead of library picker, update docs accordingly #4310
- [x] Import from expo-keep-awake instead of expo in AppEntry #4308
- [x] [android] Creating a calendar event throws a NPE if eventUri is null #4305
- [x] [docs] Add `pitchCorrectionQuality` to `expo-av` #4307
- [x] [android] Signing in with Facebook login seems not to work #4306

### Infrastructure related
- [x] Update schema on staging (@sjchmiela)
- [x] Deploy schema to production (@sjchmiela)
- [x] Release xdl and expo-cli (@sjchmiela)
- [x] Publish dev and prod home (@tsapeta)
- [x] Push iOS Turtle to staging (@tsapeta)
- [x] Push Android Turtle to staging (@sjchmiela)
- [x] Release new project templates
- [x] Update ExpoKit Android on staging (@sjchmiela)
- [x] Update ExpoKit iOS on staging (@tsapeta)
- [x] Update ExpoKit AdHoc iOS on staging (@tsapeta)
- [x] Update `versions` on staging
- [x] Publish NCL to Apple's account (@tsapeta)
- [x] Update Home to show web projects
- [x] Submit for Apple review (@tsapeta)
- [x] Release iOS in App Store (@tsapeta)
- [x] Rollout Expo Client build for Simulator ([add back bg location](https://github.com/expo/expo/pull/4325/commits/41db6eb3bfab7c4edb3dc25a7449bf6dcc62b488)) (@tsapeta)
- [x] Push Android ExpoKit (@sjchmiela)
- [x] Add Android apk (@sjchmiela)
- [x] Release Android in Play Store ([workflow](https://circleci.com/workflow-run/3ec5253d-7e87-43b3-9a73-9989a55b444e)) (@sjchmiela)
- [x] Mark old SDK as deprecated on server (@sjchmiela)
- [x] Promote versions to prod
- [x] Add SDK33 support to Snack (@tcdavis)
- [ ] Release iOS Turtle to prod
- [ ] Release Android Turtle to prod (@sjchmiela)
- [ ] Release turtle-cli
- [x] Test ad-hoc builds (@quinlanj)
- [ ] Add note about `gulp update-react-native-unimodules-expokit` to the release documentation (@sjchmiela)

### Information related
- [x] Prepare changelog (@sjchmiela)
- [x] Review changelog (@tsapeta)
- [x] Publish NCL to @ community account
- [x] Add release notes to docs
- [x] Publish blog post with release notes (@ide, @esamelson)
- [x] Update React Native docs for this SDK (@tsapeta)
- [x] Publish new docs (@tsapeta)\
- [x] Promote new docs to prod
- [x] Update website front page
- [x] Post on Twitter

**Comment by raajnadar** [comment]
Will sdk 33 be using react native v0.59.7??

The keyboard avoiding view issue is fixed here (after 1 year) https://github.com/facebook/react-native/commit/7140a7f7d15

**Comment by ide** [comment]
SDK 33 will use 0.59.8 and pin it there unless there is a critical bug (ex: many apps crashing) that requires an update. Any other upgrades will go out in a future SDK.

**Comment by serranoarevalo** [comment]
Any ETA for SDK 33?

**Comment by spyshower** [comment]
I hope we will get some fixes to the countless errors at the moment right?

**Comment by DevUsmanGhani** [comment]
Will there be anything regarding Background Location on android? There are a few threads with people having unresolved problems with getting Background Location to work on android. The task will only fire once when the app goes to the background and then not again even though it works fine on IOS.

**Comment by Gad0005** [comment]
Having same issue as @DevUsmanGhani . IOS background task seems to be firing appropriately, but I can only get Android to fire background task once. The time it does fire once, it happens "immediately" after you select the "home" button....beyond that, I cant seem to get it to fire anymore.

**Comment by tsapeta** [comment]
@DevUsmanGhani @Gad0005 Yes, #3837 is hopefully going to resolve this issue on Android - you will need to use `foregroundService` option that was added in this pull request.

**Comment by Gad0005** [comment]
OK, no problem, Ill try the pull request and stay tuned for anything additional that comes up! Thanks for the update!

**Comment by maxcaluva** [comment]
Any ETA in this one?

**Comment by ide** [comment]
We don't have an ETA but if you are interested in updates, either subscribe to this issue or to the Expo blog (https://blog.expo.io), which is where we post updates if there are any to share.

**Comment by mohsinriaz17** [comment]
so it will support 64-bit builds as opposed to the statement

> After SDK 33, we are also looking to support 64-bit APKs in time for Google’s upcoming requirement, which is also made easier by dropping older SDK versions.

> 

"After SDK 33"
https://blog.expo.io/preview-upcoming-changes-for-expo-sdk-33-67a4bac611a4

**Comment by tsapeta** [comment]
The statement in the blog post is correct, we will be working on 64-bit support right after the release of SDK33.

**Comment by mohsinriaz17** [comment]
> The statement in the blog post is correct, we will be working on 64-bit support right after the release of SDK33.

and what are the chances that 64-bit support will be available before or during August? for binaries for Google Play store

**Comment by dellwatson** [comment]
i wish bottomsheet for Android is here or similar, im waiting an Android version like ActionSheetIOS for android with native looking

**Comment by harisvsulaiman** [comment]
> i wish bottomsheet for Android is here or similar, im waiting an Android version like ActionSheetIOS for android with native looking

You build one yourself with react native gesture handler. Or use action from @expo organisation

**Comment by yareyaredesuyo** [comment]
Maybe release next month?

I think it is a good idea to add react-hooks template or example.
Because react-hooks is awesome feature and reduce a lot of boilerplate codes.

**Comment by oshimayoan** [comment]
Isn't Expo already has one?
Take a look at this one https://github.com/expo/react-native-action-sheet.

**Comment by karanpratapsingh** [comment]
Waiting for sdk33, hope this releases soon

**Comment by spyshower** [comment]
@yareyaredesuyo More like October.

**Comment by dellwatson** [comment]
@oshimayoan but it was using iOS interface, so it doesn't feel like a native in android without using android's taste

**Comment by xiCO2k** [comment]
Hey guys, thanks for the awesome job, how much days left to have it? Thanks

**Comment by karanpratapsingh** [comment]
@xiCO2k I think at least 4-5 weeks looking at their timeline

**Comment by raajnadar** [comment]
The ipa is submitted for review the estimated time is 1 week. They said android is causing a lot of blocker for rn upgrade in their blog post. And the sdk-33 branch is cut.

**Comment by stevelizcano** [comment]
I use just ExpoKit- is it possible to upgrade that now since the branch is cut?

**Comment by tomas-petrovcin** [comment]
> I use just ExpoKit- is it possible to upgrade that now since the branch is cut?
@stevelizcano 
Check the release blog posts, there's always update guide for ExpoKit as well :)

**Comment by ken0x0a** [comment]
I think, I'm checking this issue more than once a day. I can't wait upgrading!!

**Comment by karanpratapsingh** [comment]
@ken0x0a IKR, same 😆

**Comment by cmacdonnacha** [comment]
Anyone else seeing any issue with google sign in after updated to the latest Expo client in the play store?

**Comment by brentvatne** [comment]
@cmacdonnacha - care to elaborate in a new issue?

**Comment by cmacdonnacha** [comment]
@brentvatne  I created a post on the Expo forum: https://forums.expo.io/t/latest-expo-client-crashes-when-trying-to-google-sign-in/23332

I'm on Expo SDK 31 and after updated to Expo Client version 2.11.0 google sign in no longer works. It worked fine before that and didn't change any code my side. The android build also works fine, just not when using the expo client app. Someone else on that forum is also seeing the same issue. So it sounds like something was broken in the latest Expo client.

**Comment by YajanaRao** [comment]
Any update on background audio player?

**Comment by karanpratapsingh** [comment]
@YajanaRao I hope so, It's been under progress since 2018 June

**Comment by brettdh** [comment]
@YajanaRao @karanpratapsingh [The relevant PR](https://github.com/expo/expo/pull/3498) is mentioned [in the changelog](https://github.com/expo/expo/blob/master/CHANGELOG.md#3300) and present [in the docs](https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/audio.md#audiosetaudiomodeasyncmode), so it's looking good to me (though I haven't tested it yet).

**Comment by karanpratapsingh** [comment]
Thanks mate, damn sdk 33 is out 🎉🎉

**Comment by brettdh** [comment]
@karanpratapsingh not quite yet, but probably this week, it looks like?

**Comment by karanpratapsingh** [comment]
Lmao my bad, I thought it’s a release, waiting for sdk 33, thanks to all
the contributors/collaborators for their hard work

**Comment by cmacdonnacha** [comment]
Hey guys, this could be a blocker before releasing SDK 33 though: https://forums.expo.io/t/latest-expo-client-crashes-when-trying-to-google-sign-in/23332/4

**Comment by waryong322** [comment]
when I use expo sdk33 through expo-cli

I waiting long long time

please

**Comment by ide** [comment]
@cmacdonnacha we are looking into the sign-in issue (it's related to an Android screenOrientation setting on Android 8+) as the final blocker for the Android release.

**Comment by esamelson** [comment]
SDK 33 is out!! Check out the release notes [here](https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c). Please direct all questions to the [forums](https://forums.expo.io) and report issues by opening a new issue ticket on GitHub, rather than commenting further on this issue 🙂 

Thanks for all your patience and excitement, everyone! We are so excited to finally share this release with you all 🎉

**Comment by karanpratapsingh** [comment]
Thank you 😊

**Comment by cmacdonnacha** [comment]
Nice work guys!

**Comment by dctalbot** [comment]
Looks like on https://expo.io/tools under "Expo SDK supported versions" you should link the release notes: https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c

**Comment by rgordon95** [comment]
What version expokit to use with release sdk33?

**Comment by oshimayoan** [comment]
@rgordon95 You can use ExpoKit v2.11.0 - v2.11.2 should support SDK 33.

You can read it here https://github.com/expo/expo/releases from the release description.

**Comment by rgordon95** [comment]
Thank you for the response but I meant v33.0.4 etc. in package.json.
However I found it. It may be helpful to include the release list as a link
in ios and not just android guide, especially if ios is first.
