### ISSUE TITLE
[tools] Merge tools, tools-public and expotools

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#4428]
Right now we use three different kinds of tools: `tools`, `tools-public` and `tools/expotools`. They all could be merged into one solution - probably the best solution would be to merge them into `expotools` as they have the best infrastructure:

- they are self-documented (they provide `--help` flag)
- they are already in TypeScript
- they can be called from any directory of the repo
- it's easier to add new commands

However there is one thing that might be better in expotools - they don't really need to use nix - it always takes some time to rebuild them. Why not just add a wrapper that ensures expotools' build folder is up to date and rebuilds if not?

# Steps

- [x] Remove nix from expotools (#4469)
- [x] Migrate generating dynamic macros to expotools (#4591)
- [x] Remove obsolete scripts from tools-public (#4643)
- [x] Move publish-packages script from tools (#4712)
- [x] Move updating vendored modules (#4798)
- [x] Move Android versioning to expotools (#5787)
- [x] Move `android-update-rn` from tools (#6065)
- [ ] ~~Move creating iOS shell app from tools-public~~
- [ ] ~~Migrate tools to expotools~~
- [ ] ~~Remove unnecessary commands~~

**Comment by ide** [comment]
There are also some commands that are unused (like `gulp bundle` in the `tools`) that we can remove as well.

**Comment by tsapeta** [comment]
I've decided to close this issue. We migrated to expotools everything that was easily doable - the only remaining command is `ios-shell-app` but as far as I know it's also used in Turtle so it's probably better to leave it as is and remove `tools-public` entirely once we move to Turtle v2.
Any further issues related to this will be created separately.
