### ISSUE TITLE
Update Gradle, fix Gradle deprecation warnings, and update other Android build tools

### ISSUE THREAD

**Issue by ide** [expo/expo#4577]
This is an umbrella issue to upgrade the Android build tools:

- [x] Upgrade Gradle version #6045 
- [x] Upgrade Android Gradle plugin #6045 
- [x] Fix Gradle deprecation warnings #6045 
- [x] Clean up unused parts of the Gradle files (if any)
- [x] Revisit Proguard config: https://github.com/expo/expo/issues/4452
- [x] With the upgrade to RN 0.61 (in the future), we will upgrade to NDK r19c, so this doesn't need to happen now. But if it's easy to do we can look into it now.
- [x] Upgrade the Java compiler version

Here are some slightly longer-term upgrades too:

- Decide if we want to use Kotlin instead of Groovy for the Gradle files
- See if we can use the built-in annotation processor
