### ISSUE TITLE
[android] Support react-native-appearance

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#5464]
Followup of #4395

# Tasks:
- [x] upgrade `react-native-appearance` (`et` vendored modules update command) (#6162)
- [x] ensure `Expo Client/Home` behaves accordingly to selected system appearance (#6162)
- [x] encapsulate system appearance per Experience in `Expo Client` (#6162)
