### ISSUE TITLE
Ship SDK 35

### ISSUE THREAD

**Issue by esamelson** [expo/expo#5564]
Prerequisites

- [x] update vendored modules (@sjchmiela) - #5514 
- [x] merge Apple Authentication (@esamelson) - #5421 
- [x] update schema on staging
- [x] Cherry-pick RN commits (#5494)

### Expo client

- [x] iOS unversioned QA (@tsapeta)
- [x] iOS version SDK 35 (@tsapeta)
- [x] Android unversioned QA (@esamelson)
- [x] Android version SDK 35 (@esamelson)
- [x] Generate new mocks and update jest-expo (@Szymon20000)
- [x] Publish prerelease packages to npm (@tsapeta)
- [x] Android versioned Expo client QA (@esamelson)
- [x] iOS versioned Expo client QA (**<-- WAIT for iOS 13 GM to do this**) (@Szymon20000)
- [x] publish NCL to Apple Review account
- [x] publish prod home
- [x] Submit iOS client to Apple

### Custom client

- [x] Build iOS client shell app, deploy to turtle
- [ ] QA iOS client shell app

### ExpoKit

- [x] iOS ExpoKit QA
- [x] iOS tag ExpoKit and update on staging `versions`
- [x] Android - update `expoview` and QA (@esamelson)
- [x] Update expokit-npm-package, publish RC version, and update on staging `versions` (@esamelson)

### Turtle / infra

- [x] update schema on staging
- [x] update versions on staging
- [x] build iOS shell app and deploy to turtle staging
- [x] iOS turtle QA
- [x] Android standalone app QA (`et android-shell-app`) (@esamelson)
- [x] build Android shell app and deploy to turtle staging (@esamelson)
- [x] Android turtle QA (@esamelson)

tasks related to releasing/production will be added later in a separate comment

(reference: [SDK 34 release issue](https://github.com/expo/expo/issues/4437) , [SDK 35 project board](https://github.com/orgs/expo/projects/3))

**Comment by esamelson** [comment]
### Packages

- [ ] tag `sdk-35.0.0` on RN fork
- [ ] Publish final packages to npm
- [ ] QA project templates
- [ ] Publish project templates

### Client

- [ ] Release iOS in App Store
- [ ] Add iOS simulator build
- [ ] Release Android client in Play Store
- [ ] Add Android apk to server

### ExpoKit & Turtle

- [ ] Release turtle-cli
- [ ] Promote iOS turtle to prod
- [ ] Promote Android turtle to prod
- [ ] Promote iOS expokit tag to prod
- [ ] `et android-update-expokit`

### Other stuff

- [ ] Add SDK 35 support to snack
- [ ] Add new docs
- [ ] Publish NCL to community account
- [ ] Release notes
- [ ] Add release notes to docs
- [ ] Update website front page
- [ ] Post on Twitter
