### ISSUE TITLE
Extract SplashScreen to unimodule

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#6014]
## 🛠 Refactor

Extract `SplashScreen` to `unimodule`.

### Outline

- [x] create `expo-splash-screen` unimodule with API conforming to [docs](https://docs.expo.io/versions/latest/sdk/splash-screen/) and [configuration](https://docs.expo.io/versions/latest/workflow/configuration/#splash).
- [x] ensure `bare` workflow works
	- [x] on iOS
	- [x] on Android 
- [ ] ~~ensure `managed` workflow works~~
- [x] ensure seamless transition between `native` static splashscreen (static image in `cover`, `contain` or `native` mode) and JS-managed dynamic splashscreen (gif/animation or/and loading bar as enhancement over static image)
- [x] review API documentation
	- [x] provide new up-to-date examples with snacks
	- [ ] ~~rewrite guide for configuration and usage~~

### Known issues that have to be resolved/fixed:
- [ ] flickering/flashing `Image` component during transitioning from native splashscreen to JS-handled splashscreen continuation #4076
- [ ] `Image` component with `contain` mode on Android undesired resizing #4076
- [ ] `SplashScreen#hide()` does not work #4243 #2409
- [ ] `cover` mode issue #2399

> **Further work will be done in separate PRs (defined by separate issues).**

**Comment by esamelson** [comment]
Thanks for this detailed checklist! Since the SplashScreen and AppLoading modules are similar and closely related it would be great to extract them both at the same time.

I would add to your list that since the installation process for these modules is likely going to have more steps than for other modules, it would be good to get a feel for that early on, and write up the documentation for that and test it as well. And if any part of this is getting out of hand or seeming bigger than expected, please check in with @tsapeta or myself! 🙂

**Comment by nandorojo** [comment]
Do you think this will make it to sdk 37? Thanks for the great work!

**Comment by bbarthec** [comment]
@nandorojo SDK37 release would introduce `expo-splash-screen` unimodule that's going to support 
only `bare` workflow at the time of publishing.

**Comment by nandorojo** [comment]
Great!

**Comment by Hirbod** [comment]
Moved to SDK 38? So is the last statement still valid?

**Comment by tsapeta** [comment]
@Hirbod It's still valid, just not fully valid 😄 As you may already noticed, we started SDK37 release process for the client and since this process takes some time, it will be without SplashScreen extracted to the unimodule, but our plan is to publish some unimodules for bare workflow separately - that means these new unimodules won't be available in Expo client and SDK37, but they will be available for bare workflow at some close point (hopefully at the same time).
It shouldn't be a problem for people using managed workflow as these modules will still be available for them from `expo` package (at least in SDK37).
