### ISSUE TITLE
Expo Credentials Umbrella Issue

### ISSUE THREAD

**Issue by quinlanj** [expo/expo#6259]
# Overview
This is the umbrella issue to track the effort to make credentials easier to use in our build service.

## iOS Documentation
- [x] not entirely clear what each credential is for and how it can be used (multiple apps? what happens if i revoke it while my app is live?) https://github.com/expo/expo/issues/6196
- [x] not clear that provisioning profile depends on dist cert https://github.com/expo/expo/issues/6196

## iOS
- [x] Check credentials against Apple so we know they are still good before showing them as an option. (@quinlanj)
- [x] Only create credentials once we know it will work.  when you run `expo build:ios` the cli goes through the process of asking if it should use certain existing credentials or generate new ones. If the command fails on a later credential (let's say you elected to create another PN key when you already had 2. if you created a new dist cert before that, then the cli errors out after the PN key error *but the dist cert has been created and is now in your apple developer credentials.* (@quinlanj)
- [x] Revoke credentials from command line instead of telling people to go to the Apple developer portal (@quinlanj)

## Android
- [ ] Should automatically back up the keystore. We get a few write-ins a month about people asking for their old keystore after they accidentally clear theirs. I think it's too easy to clear your credentials right now. I know there's an easiness to having it be one command `expo build:android` and you get your app, but I think once we have credentials for your app, you can't just pass a `-c` flag and clear them. instead, maybe a separate command altogether

## Longterm
-  a GUI would be nice for people

**Comment by fson** [comment]
Also related: https://github.com/expo/expo-cli/issues/620

**Comment by tsapeta** [comment]
Looks like everything has been done, so I'm closing it.
