### ISSUE TITLE
Ship SDK 36

### ISSUE THREAD

**Issue by esamelson** [expo/expo#6264]
Prerequisites

- [x] Fix iOS versioning (@tsapeta) - #6131 
- [x] update schema on staging

### Expo client

- ~Drop old SDK versions~ not dropping any this release
- [x] iOS unversioned QA (@tsapeta)
- [x] iOS version SDK 36 (@tsapeta) #6307
- [x] Android unversioned QA (@esamelson)
- [x] Android version SDK 36 (@esamelson) #6281
- [x] Generate new mocks and update jest-expo (@tsapeta)
- [x] Publish prerelease packages to npm (@tsapeta)
- [x] Android versioned Expo client QA (@esamelson)
- [x] iOS versioned Expo client QA (@tsapeta)
- [x] publish NCL to Apple Review account (@tsapeta)
- [x] publish prod home (@esamelson)
- [x] Submit iOS client to Apple (@tsapeta)
- [x] Send TestFlight invitations, Android APK(?) to beta testers

### Custom client

- [x] Build iOS client shell app, deploy to turtle
- [ ] QA iOS client shell app

### ExpoKit

- [ ] iOS ExpoKit QA
- [x] iOS tag ExpoKit and update on staging `versions`
- [x] Android - update `expoview` and QA (@esamelson)
- [x] Update expokit-npm-package, publish RC version, and update on staging `versions` (@esamelson)

### Turtle / infra

- [x] update schema on staging
- [x] update versions on staging
- [x] build iOS shell app and deploy to turtle staging
- [x] iOS turtle QA
- [x] Android standalone app QA (`et android-shell-app`) (@esamelson)
- [x] build Android shell app and deploy to turtle staging (@esamelson)
- [x] Android turtle QA (@esamelson)

tasks related to releasing/production will be added later in a separate comment

(reference: [SDK 36 project board](https://github.com/orgs/expo/projects/4))

**Comment by esamelson** [comment]
### Packages

- [ ] tag `sdk-36.0.0` on RN fork
- [ ] Publish final packages to npm
- [ ] QA project templates
- [ ] Publish project templates
- [ ] Promote project templates to latest on npm

### Client

- [ ] Release iOS in App Store
- [ ] Add iOS simulator build
- [ ] Release Android client in Play Store
- [ ] Add Android apk to server

### ExpoKit & Turtle

- [ ] Release turtle-cli
- [ ] Promote to latest on NPM
- [ ] Release iOS turtle to prod
- [ ] Release Android turtle to prod
- [ ] Promote iOS expokit tag to prod
- [ ] `et android-update-expokit`

### Other stuff

- [ ] Add SDK 35 support to snack
- [ ] Add new docs (inc. update RN docs if needed)
- [ ] Publish NCL to community account
- [ ] Release notes
- [ ] Add release notes to docs
- [ ] Deprecate old SDK versions
- [ ] Update website front page
- [ ] Post on Twitter
