### ISSUE TITLE
Ship SDK 37

### ISSUE THREAD

**Issue by esamelson** [expo/expo#7173]
### [1. Versioning](https://git.io/JeKCx#stage-1---versioning)

- [x] [1.1. Dropping old SDKs](https://git.io/JeKCx#11-dropping-old-sdks)
  - [x] Android
  - [x] iOS
- [x] [1.2. Update React Native](https://git.io/JeKCx#12-update-react-native)
- [x] [1.3. Unversioned Quality Assurance](https://git.io/JeKCx#13-unversioned-quality-assurance)
  - [x] Android
  - [x] iOS (@bbarthec)
- [x] [1.4. Versioning code for the new SDK](https://git.io/JeKCx#14-versioning-code-for-the-new-sdk)
  - [x] Android
  - [x] iOS #7219 (@bbarthec)

### [2. Quality Assurance](https://git.io/JeKCx#stage-2---quality-assurance)

- [x] [2.1. Versioned Quality Assurance](https://git.io/JeKCx#21-versioned-quality-assurance)
  - [x] Android
  - [x] iOS #7222 (@bbarthec)
- [x] [2.2. Publish demo apps](https://git.io/JeKCx#22-publish-demo-apps)
	- [x] Publish to `applereview` account
	- [x] Publish to `community` account

### [3. Prerelease](https://git.io/JeKCx#stage-3---prerelease)

- [x] [3.1. Tag React Native fork](https://git.io/JeKCx#31-tag-react-native-fork) #7241 (@bbarthec)
- [x] [3.2. Generate new mocks](https://git.io/JeKCx#32-generate-new-mocks) #7243 (@bbarthec)
- [x] [3.3. Publishing prerelease packages](https://git.io/JeKCx#33-publishing-prerelease-packages) (@bbarthec)
- [x] [3.4. Publishing prerelease project templates](https://git.io/JeKCx#34-publishing-prerelease-project-templates) #7279 (@bbarthec)

### [4. Expo client](https://git.io/JeKCx#stage-4---expo-client)

- [x] ~[4.1. Cutting off release branch](https://git.io/JeKCx#41-cutting-off-release-branch)~
- [x] [4.2. Releasing beta version](https://git.io/JeKCx#42-releasing-beta-version)
  - [x] Android
  - [x] iOS
- [x] [4.3. Making a simulator build](https://git.io/JeKCx#43-making-a-simulator-build)
  - [x] Android
  - [x] iOS
- [x] [4.4. Submitting to the stores](https://git.io/JeKCx#44-submitting-to-the-stores)
  - [x] Android
  - [x] iOS

### [5. ExpoKit and standalone apps](https://git.io/JeKCx#stage-5---expokit-and-standalone-apps)

- [x] [5.1. Updating ExpoKit](https://git.io/JeKCx#51-updating-expokit)
  - [x] Android
  - [x] iOS
- [x] [5.2. Make shell app build](https://git.io/JeKCx#52-make-shell-app-build)
  - [x] Android
  - [x] iOS https://github.com/expo/turtle/pull/194 [CircleCI job with shellApp](https://app.circleci.com/pipelines/github/expo/expo/14143/workflows/89b2c9d7-549b-4ac9-a3a7-458b78d14239/jobs/132304)
- [x] [5.3. Make adhoc client shell app](https://git.io/JeKCx#53-make-adhoc-client-shell-app) https://github.com/expo/turtle/pull/194 [CircleCI job with Adhoc Expo Client](https://app.circleci.com/pipelines/github/expo/expo/14143/workflows/c45b362d-f62f-4413-85bf-6d5167efce27/jobs/132434)
- [x] 5.4-a THIS RELEASE ONLY -- merge PRs upgrading turtle to node 12! ([first](https://github.com/expo/turtle-deploy/pull/7), [second](https://github.com/expo/turtle/pull/186))
- [x] [5.4. Deploy Turtle with new shell tarballs](https://git.io/JeKCx#54-deploy-turtle-with-new-shell-tarballs)
  - [x] Android
  - [x] iOS (both archive (`ipa`) and simulator builds types works - tested on TestFlight)

### [6. Final release](https://git.io/JeKCx#stage-6---final-release)

- [x] [6.1. Publishing final packages to NPM registry](https://git.io/JeKCx#61-publishing-final-packages-to-npm-registry)
- [x] [6.2. Publishing final project templates](https://git.io/JeKCx#62-publishing-final-project-templates)
- [x] [6.3. Generate and deploy new docs](https://git.io/JeKCx#63-generate-and-deploy-new-docs)

### [7. Snack](https://git.io/JeKCx#stage-7---snack)

- [x] [7.1. Add SDK support to Snack](https://git.io/JeKCx#71-add-sdk-support-to-snack)

### [8. Press release](https://git.io/JeKCx#stage-8---press-release)

- [x] [8.1. Publish a blog post](https://git.io/JeKCx#81-publish-a-blog-post)
- [x] [8.2. Post on Twitter](https://git.io/JeKCx#82-post-on-twitter)

### Additional things:

- [x] https://github.com/expo/turtle/pull/186
