### ISSUE TITLE
SDK 37 Android Keyboard master issue

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#7815]
- "[Android] KeyboardAvoidingView is Pushing the Input way upward " https://github.com/expo/expo/issues/7666
- "Views are moved by the Keyboard opening even when not wrapped in a KeyboardAvoidingView" https://github.com/expo/expo/issues/7589
- Possible inconsistency between keyboard resize behaviour in Expo client vs standalone app https://github.com/expo/expo/issues/7814

## Current status

@bbarthec has put together this repository to demonstrate the behaviors react-native's `KeyboardAvoidingView` and `View` in bare React Native apps and managed apps: https://github.com/bbarthec/expo-issues/tree/master/7589-KeyboardAvoidingView. In short, **managed workflow behaviour is the same as bare React Native 0.61.5 behaviour.** It is, however, different from Expo SDK 36 behaviour, despite using the same React Native version.

## To do

- [ ] Investigate #7814 about inconsistency between behaviour in Expo client vs standalone app.
- [ ] Document how to update apps to achieve the same behaviour as in SDK 36 in SDK 37.
- [ ] Investigate whether `View` behaving always as `KAV` in upstream is desirable.

**Comment by Rohansi** [comment]
https://github.com/facebook/react-native/commit/e3d4ace3ae46e3e4046e1ec5a201b92033deb24a
> Let's use "adjustResize", it seems to be a reasonable default in most cases and people can always change the constant in their AndroidManifest.xml

Ouch.

**Comment by brentvatne** [comment]
@Rohansi - not sure what you mean. that commit has been around since react-native@0.42

**Comment by Rohansi** [comment]
That should be when the behavior was introduced into React Native. In Expo it's probably something like this: https://github.com/expo/expo/pull/6506/commits/f9b06563f099f9c9b0d0a29090f96f913b9ffab4#diff-6a6b114fae7509c7402c5f5d3866aa07

With this behavior there seems to be no point to `KeyboardAvoidingView` on Android. Your app will shrink and adjust to fit instead of being tucked under the keyboard. In fact - you can't even use a `KeyboardAvoidingView` on Android or it'll add a huge gap where the keyboard *should* be.

I don't agree with the inconsistency between Android and iOS, even if that's what RN does, because it's really annoying to work with. There are [ways to change the `adjustResize` flags at runtime](https://github.com/zubricky/react-native-android-keyboard-adjust) which could allow adding it as an option into the Expo config. That way it'd match what RN want us to do anyway.

**Comment by Blackoutseeker** [comment]
I need this working! And i update my issue with more info (#7814 ).

**Comment by bbarthec** [comment]
Regarding mis-behavior of `View` and `KeybaordAvoidingView` components and recent change that made apps written in SDK37 behave the same way as apps in plain ReactNative, I've created [this snack](https://snack.expo.io/@bbarthec/github---keyboardavoidingview) with possible solution.

Possible solution is to ensure that the soft keyboard will not cause your application height will shrink every time the keyboard appears (without this one, application will behave as @Rohansi wrote in his comment).

In general, everything that has to be done is to explicitly set root View height.
```tsx
const RootComponentOfYourApp = () => {
  const { height: windowHeight } = Dimensions.get('window'); // window always returns height as if the application can draw under StatusBar
  const statusBarHeight = StatusBar.currentHeight || 0;
  // when we are unable to render under StatusBar (and this is only when StatusBar is visible and non-translucent)
  // then we need to subtract it's height from window height
  const rootViewHeight = windowHeight - ((!statusBarHidden && !statusBarTranslucent) ? statusBarHeight : 0);

  return (
    <View style={[styles.rootContainer, { height: rootViewHeight }]}>
      {...application logic}
    </View>
  );
}

const styles = StyleSheet.create({
  rootContainer: { ... },
  ...
});
```

**Comment by ConorWatsonSoar** [comment]
I can confirm that solution posted by @bbarthec works on our Production app with SDK37, although for a quick test on my Samsung S10+ I had to set both `statusBarHidden` and `statusBarTranslucent` flags to `true`. I'd need to check if this was the case for all Android phones running our app.

Is this only intended as a stop-gap solution, or is this the final solution that is being suggested by the Expo team?

**Comment by pantelispanayiotou** [comment]
@bbarthec  saves the day but i believe it's a workaround, @ConorWatsonSoar  can confirm that i also had to enable statusBarHidden and statusBarTranslucent, hopefully i used a background image so that didn't hurt at all.

**Comment by Rohansi** [comment]
That's a decent workaround for now. I've also tried using `useWindowDimensions` in place of `Dimensions.get` but that hook locks up my app apparently.

**Comment by Rohansi** [comment]
@bbarthec I tested on additional phones and found that you do indeed need to hide the status bar as well - but not for all phones. My Moto e5 cruise and Samsung S7 edge were fine with a translucent status bar and the root view matching the window height. However, with the same code the root view is too short for a Samsung S10+. For that I need to add the status bar height so the rot view fills the screen as it should.

The S10+ has the camera in the screen, which probably plays a part in these differences, but I don't see how to workaround this without disabling the status bar. The top safe area inset is equal to the status bar height across all three of these phones.

**Comment by Rohansi** [comment]
@bbarthec That workaround also introduces a gap at the bottom of the screen on the iPhone X. Same reason as the Samsung S10+.

**Comment by SimenB** [comment]
Encountered this as well. Was able to resolve it by removing a hack added for earlier SDKs.

```diff
 const keyboardAvoidingViewBehavior =
-  Platform.OS === 'ios' || !__DEV__ ? 'padding' : undefined;
+  Platform.OS === 'ios' ? 'padding' : undefined;
```

Essentially, we set `padding` in standalone app before (but not when using expo client), same as for iOS. For SDK 37 I had to remove it so it's only set for iOS

**Comment by Rohansi** [comment]
FWIW, in the app I'm working on, the behavior `padding` used to work nicely across all targets.

That workaround also doesn't play nicely with React Navigation's bottom tabs because the tabs get pushed up above the keyboard, but only the tab contents are in a `KeyboardAvoidingView` so the tab bar itself should stay put.

**Comment by Rohansi** [comment]
@bbarthec  Update?

**Comment by bbarthec** [comment]
@Rohansi, as `KeyboardAvoidingView` seems not to work consistently on Android platform, we're discussing internally what should be done in this matter. Hopefully we'll find some valid solution soon 🤔

**Comment by Rohansi** [comment]
Is there any chance of this being fixed in SDK 37 soon? Because if not I will need to downgrade to SDK 36 and upgrade later.

**Comment by Rohansi** [comment]
@bbarthec Following up - can I have an estimated day when this would be fixed?

**Comment by brentvatne** [comment]
@Rohansi - can you describe what you expect a fix to do?

**Comment by outaTiME** [comment]
@brentvatne IMHO it should work as in the previous version of the SDK using `undefined` as `keyboardAvoidingViewBehavior` for android does not produce the same result. 

https://github.com/expo/expo/issues/7589#issuecomment-610058128

**Comment by brentvatne** [comment]
@bbarthec has been investigating providing an option to let people opt-in to the behavior of their choice on a per-screen basis, i’ll let him speak to that more

**Comment by Rohansi** [comment]
@bbarthec  I'd expect it to work like before because `KeyboardAvoidingView` worked well and had pretty consistent behavior across iOS and Android.

I don't know the full story behind [this commit](https://github.com/facebook/react-native/commit/e3d4ace3ae46e3e4046e1ec5a201b92033deb24a) but it seems to ignore the existence of `KeyboardAvoidingView` in favor of shrinking the root view. From the screenshots in the commit message it looks like the behavior before was to push the root view up without resizing.

For compatibility with RN as a whole those modes need to be exposed in Expo - simply because RN suggests that people change it to suite their needs. Personally I would have been fine with an option in `app.json` but being able to configure it per screen sounds perfect - though what is a screen in this case?

**Comment by imshreyansh** [comment]
+1

**Comment by MStonehouse** [comment]
Is there any idea of when this might be resolved? The solution provided by @bbarthec does not seem to work consistently across all devices. Is it at least possible to get adjustPan back in the mix ASAP so I don't have to go back and figure out solutions for all the apps I've already made?

**Comment by MStonehouse** [comment]
Is there any idea of when this might be resolved? The solution provided by @bbarthec does not seem to work consistently across all devices. Is it at least possible to get adjustPan back in the mix ASAP?

**Comment by Rohansi** [comment]
I'm going to be reverting to SDK 36 this Friday. That'll fix it but only for standalone builds.

**Comment by dvester** [comment]
I am not currently using a KeyboardAvoidingView. Just showing the status bar is causing the screen to automatically resize to make room for the keyboard. This makes animations very hard to code for as it does not working consistently across iOS and Android. It also looks very bad with the newer android phones that have a notch. Since we can't control it on a per screen basis (also screens don't really make sense in react native world), we need the component to handle this behavior (KeyboardAvoidingView).

**Comment by Rohansi** [comment]
Well lots of my Reanimated code is broken (among many other things) so there goes all hopes of reverting to SDK 36. I guess I'm stuck waiting on you guys for a fix.

**Comment by Rohansi** [comment]
@bbarthec The problem with your workaround is the window dimensions are currently flawed. I don't believe there is any way around this problem at the moment.

https://github.com/facebook/react-native/issues/23693

**Comment by nero2009** [comment]
> Encountered this as well. Was able to resolve it by removing a hack added for earlier SDKs.
> 
> ```diff
>  const keyboardAvoidingViewBehavior =
> -  Platform.OS === 'ios' || !__DEV__ ? 'padding' : undefined;
> +  Platform.OS === 'ios' ? 'padding' : undefined;
> ```
> 
> Essentially, we set `padding` in standalone app before (but not when using expo client), same as for iOS. For SDK 37 I had to remove it so it's only set for iOS

This worked for me

**Comment by Rohansi** [comment]
I ended up using a hybrid of two workarounds for this. For Android phones I'm [taking this path](https://github.com/facebook/react-native/issues/23693#issuecomment-523640102) because I lock them to portrait. For Android tablets I'm falling back to [this one](https://github.com/expo/expo/issues/7815#issuecomment-614721573) minus the `StatusBar` stuff. iOS and others don't need any of this of course.

I haven't spotted any issues with this yet but its a horrible workaround for something that should be simple!

**Comment by wdacoinin** [comment]
Solve my code with this. (Gboard on xiaomi)

const deviceHeight = Dimensions.get("window").height;
more code...

<SafeAreaView style={styles.container}>
                <StatusBar barStyle='light-content' />
                    <KeyboardAvoidingView behavior='padding' style={styles.container} enable>
                    
                        <TouchableWithoutFeedback style={styles.container} onPress={Keyboard.dismiss}>

more code...

</TouchableWithoutFeedback>
</KeyboardAvoidingView>
</SafeAreaView>


const styles = StyleSheet.create({
    
    container: {
        height:deviceHeight*1,
        backgroundColor: 'rgb(32, 53, 70)',
        flexDirection: 'column'
    },
})

**Comment by Rohansi** [comment]
> Solve my code with this. (Gboard on xiaomi)
> 
> const deviceHeight = Dimensions.get("window").height;

FYI this will not work on Android devices with a notch because `Dimensions.get("window")` gives the wrong numbers on those devices. This solution will leave a gap at the bottom of your app for those devices - but that's probably preferable to completely broken keyboard avoiders!

**Comment by brentvatne** [comment]
we've added a new property to app configuration so you can switch from resizing the window when the keyboard opens to panning using this config:

```
"android": {
  "softwareKeyboardLayoutMode": "pan"
}
```

with this config, notice that the tab bar isn't pushed up by the keyboard.

![pan](https://user-images.githubusercontent.com/90494/84935465-9a127680-b08d-11ea-8db5-82187f960bc6.gif)

**Comment by med4it** [comment]
@brentvatne  ` "softwareKeyboardLayoutMode": "pan"` did not make a diffrence for me!

**Comment by samkovaly** [comment]
@brentvatne Works wonders! Thank you.

**Comment by brentvatne** [comment]
@med4it - i don't know what you are expecting it to do, but the confusion does work on sdk 38 to change the resize keyboard resize mode.
