### ISSUE TITLE
Support react-native-web@0.12

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#8064]
- [`react-native-web@0.12`](https://github.com/necolas/react-native-web/releases/tag/0.12.0) maps roughly to `react-native@0.62` which we will support in Expo SDK 38.
- RNW v12 is slightly ahead of RN by way of deprecation, so somethings that have been removed in `react-native-web` haven't been removed in `react-native` yet. We can jump ahead of `react-native` and start removing things immediately.
- RNW v12 [Release Notes](https://github.com/necolas/react-native-web/releases/tag/0.12.0)

## TODO

- [x] Delete prop types https://github.com/necolas/react-native-web/commit/1ad16930391303da511c98879fa7b2002b28c822 - prop-types are deprecated in [`react-native`](https://github.com/facebook/react-native/blob/851d01b0aa45285bd6a52c89ab9c1b64a637258e/index.js#L479-L491) - #8675 #8676 #8677 #8678 #8679 #8680 #8681 
  - Will leave `expo-payments-stripe` alone for now since it doesn't have web support.
- Remove the following modules: 
  - AsyncStorage
    - [x] Remove from `expo-notifications`
    - [x] Remove from NCL https://github.com/expo/expo/pull/9018
  - [x] AlertIOS 
  - ActionSheetIOS
    - [x] Remove from NCL
    - [ ] Remove from `react-navigation-header-buttons`
  - [x] CameraRoll
  - [x] DatePickerAndroid
  - [x] DatePickerIOS
  - [x] ImageEditor
  - [x] ImagePickerIOS
  - [x] ImageStore
  - [x] ListView
  - MaskedViewIOS
    - [ ] Ensure shim / warning - [community/react-native-masked-view](https://github.com/react-native-community/react-native-masked-view)
    - [ ] Integrate module
    - [ ] Swap in NCL
  - [x] NavigatorIOS
  - NetInfo
    - [ ] Add legacy web support 
    - [x] Integrate module
    - [x] Swap in NCL
  - PickerIOS
    - [x] Add legacy web support [community/react-native-picker](https://github.com/react-native-community/react-native-picker/pull/88)
    - [x] Integrate module
    - [x] Swap in NCL
  - [x] ProgressBarAndroid
  - [x] ProgressViewIOS
  - [x] PushNotificationsIOS
  - SegmentedControlIOS
    - [x] Add legacy web support
    - [x] Integrate module
    - [x] Swap in NCL
  - Slider
    - [x] Add legacy web support
    - [x] Integrate module
    - [x] Swap in NCL
  - [x] SnapshotViewIOS
  - [x] StatusBarIOS
  - [x] SwipeableListView
  - [x] ToolbarAndroid
  - [x] VibrationIOS
  - ViewPagerAndroid
    - [ ] Add web shim / warning
    - [ ] Integrate module
    - [ ] Swap in NCL
  - WebView
    - [ ] Add legacy web support
    - [ ] Integrate module
    - [ ] Swap in NCL
- More TBD

**Comment by LinusU** [comment]
@EvanBacon it seems like this didn't make it in time for SDK 38? Is it possible to upgrade anyways, or do we have to wait until SDK 39? Thanks

**Comment by chrisdrackett** [comment]
I'm using RNW `0.12` in SDK 38 without issue
