### ISSUE TITLE
[expo-notifications] Integration with Expo Client

### ISSUE THREAD

**Issue by lukmccall** [expo/expo#8135]
Follow up to https://www.notion.so/expo/Integration-with-Expo-Client-a9e57769edec46ebaab5a4ebc8db1584

# TODO
- [x] add expo-notifications to the projects (by https://github.com/expo/expo/pull/8094)
- [x] make expo-notifications the top manager (by https://github.com/expo/expo/pull/8139)
- [x] integrate old infrastructure into the new, expo-notifications-based one (by https://github.com/expo/expo/pull/8175)
- [x] add scoping 
  - [x] add scoped subclass for notifications emitters (by https://github.com/expo/expo/pull/8265)
  - [x] add scoped subclass for notifications handlers (by https://github.com/expo/expo/pull/8268)
    - [x] see if we need to scope notification builders too
  - [x] add scoped subclass for notifications schedulers (by https://github.com/expo/expo/pull/8350 & https://github.com/expo/expo/pull/8361)
- [x] ~add scoped module for permissions~ - will be added later
- [x] fix click handler on android (by https://github.com/expo/expo/pull/8378)
- [x] ~we'll need to make sure that the notification passed into initialProps is somehow delivered to expo-notifications listeners 🍏~ - will be added later
