### ISSUE TITLE
Remove .0.0 from SDK versions master issue

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#8255]
Getting the ball rolling on this by listing out places where we currently refer to three-part sdk version, eg: 37.0.0, rather than just 37.

- [ ] Docs path, eg: https://docs.expo.io/versions/v37.0.0/sdk/accelerometer/
- [ ] Anywhere in docs where we mention it, eg: https://docs.expo.io/versions/latest/#each-expo-sdk-version-depends-on-a
- [ ] expo-cli commands, eg: publish related

**Comment by jkhales** [comment]
https://github.com/expo/universe/blob/master/server/www/src/apiv2/utils.ts#L92
