### ISSUE TITLE
Umbrella issue for Android permission changes

### ISSUE THREAD

**Issue by byCedric** [expo/expo#9499]
## Overview

After issue #8942 was reported, we started an audit to see if we have more "weird" Android permission definitions elsewhere. Eventually, I concluded a couple of issues:

- Some permissions, like `REQUEST_INSTALL_PACKAGE` should never be included by default.
- If developers are surprised about the added Android permissions, we don't communicate this very well.
- It's hard to look up what permissions are required per module.
- It's impossible to remove Android permissions when they are not blacklisted in the [XDL's blacklist](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/detach/AndroidShellApp.js#L780).
- All required `infoPlist` messages are really hard to find.

## Solving the issues

We [fixed the initial `REQUEST_INSTALL_PACKAGE` issue in `expo-device`](https://github.com/expo/expo/pull/8969), to resolve #8942. For the other issues, we want to tackle them in this order.

![permission-stages](https://user-images.githubusercontent.com/1203991/88941506-5fede480-d289-11ea-9e7f-c74d7fa333cf.png)

### Transparency

- Update permissions docs and include `infoPlist` messages and Android permissions
  * [x] https://github.com/expo/expo/pull/9141
- Document what permissions are required per module.
  * [x] https://github.com/expo/expo/pull/9224
  * [x] https://github.com/expo/expo/pull/9227
  * [x] https://github.com/expo/expo/pull/9230
  * [x] https://github.com/expo/expo/pull/9231
  * [x] https://github.com/expo/expo/pull/9442
  * [x] https://github.com/expo/expo/pull/9445
  * [x] https://github.com/expo/expo/pull/9447
  * [x] https://github.com/expo/expo/pull/9492
  * [x] https://github.com/expo/expo/pull/9494
  * [x] https://github.com/expo/expo/pull/9495
  * [x] https://github.com/expo/expo/pull/9496
  * [x] https://github.com/expo/expo/pull/9497 
- [x] Update XDL Schema description with core Expo permissions added.
  * https://github.com/expo/universe/pull/5548

### Maintainability 

- [x] Add danger script to remind contributors of adding permissions to [XDL's backlist](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/detach/AndroidShellApp.js#L780) as well.
  * https://github.com/expo/expo/pull/9708

### Improvements

- [x] Expand XDL's blacklist with missing permissions.
  * ~~https://github.com/expo/expo-cli/pull/2307~~
  * https://github.com/expo/expo-cli/pull/2458 
- [x] Clean up template files to remove signature or non-3rd-party permissions.
  * https://github.com/expo/expo/pull/9727
- [ ] Minimize the different locations where permissions are listed (e.g. remove some from ShellApp and inherit from `expo-*` modules.)
- [ ] Discuss making `WRITE_*` permissions more opt-in (e.g. [`expo-contacts`](https://github.com/expo/expo/blob/master/packages/expo-contacts/android/src/main/java/expo/modules/contacts/ContactsModule.java#L101-L105))
